export const FILE_LIST_REQUEST_SUCCESS = 'SOULIKE_DRIVE/FILE_LIST/FILE_LIST_REQUEST_SUCCESS';

export const FILE_LIST_REQUEST_FAILED = 'SOULIKE_DRIVE/FILE_LIST/FILE_LIST_REQUEST_FAILED';

export const FILE_DELETE_SUCCESS = 'SOULIKE_DRIVE/FILE_LIST/FILE_DELETE_SUCCESS';

export const FILE_DELETE_FAILED = 'SOULIKE_DRIVE/FILE_LIST/FILE_DELETE_FAILED';

export const FILE_DOWNLOAD_SUCCESS = 'SOULIKE_DRIVE/FILE_LIST/FILE_DOWNLOAD_SUCCESS';

export const FILE_DOWNLOAD_FAILED = 'SOULIKE_DRIVE/FILE_LIST/FILE_DOWNLOAD_FAILED';

export const FILE_SELECTED = 'SOULIKE_DRIVE/FILE_LIST/FILE_SELECTED';

export const FILE_UNSELECTED = 'SOULIKE_DRIVE/FILE_LIST/FILE_UNSELECTED';
