export const LOGIN_SUCCESS = 'AUTH_PROCESSOR/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'AUTH_PROCESSOR/LOGIN_FAILED';

export const LOGOUT_SUCCESS = 'AUTH_PROCESSOR/LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'AUTH_PROCESSOR/LOGOUT_FAILED';

export const LOGIN_STATE_VALID = 'AUTH_PROCESSOR/LOGIN_STATE_VALID';
export const LOGIN_STATE_INVALID = 'AUTH_PROCESSOR/LOGIN_STATE_INVALID';
